브로드캐스팅 연산
- 두 배열간의 형상을 맞춘다
- ![image.png]()

In [2]:
import numpy as np


# 브로드캐스팅을 사용X
x = np.array([1,2,3,4,5])
y = np.array([1,1,1,1,1])
print(x+y)

# 브로드캐스팅을 사용한 경우
y = 1
print(x+y)

[2 3 4 5 6]
[2 3 4 5 6]

브로드캐스팅 연산
  - shape가 다른 두 배열의 연산
    1. shape가 다른 두 배열 사이의 이항연산에서 브로드캐스팅이 발생
    2. 두 배열을 같은 shape로 만든 후 연산 수행

In [5]:
# shape가 다른 두 배열의 연산
a = np.arange(1,25).reshape(4,6)
print(a*100)   # 브로드캐스팅

print("------과정------")
print("--1. 스칼라의 배열 변경--")
new = np.full_like(a, 100)
print(new)
print("--2. 배열 이항 연산--")
print(a*new)

[[ 100  200  300  400  500  600]
 [ 700  800  900 1000 1100 1200]
 [1300 1400 1500 1600 1700 1800]
 [1900 2000 2100 2200 2300 2400]]
------과정------
--1. 스칼라의 배열 변경--
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
--2. 배열 이항 연산--
[[ 100  200  300  400  500  600]
 [ 700  800  900 1000 1100 1200]
 [1300 1400 1500 1600 1700 1800]
 [1900 2000 2100 2200 2300 2400]]

In [9]:
# shape가 다른 배열 연산
a = np.arange(5).reshape(1,5)
print(a)
b = np.arange(5).reshape(5,1)
print(b)
print(a+b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

벡터
  - n차원 공간에서 방향과 크기를 갖는 단위
  - np.array() 배열객체(ndarray)를 사용해서 벡터를 생성

배열변환
  - 전치 : 행렬의 인덱스가 바뀌는 변환

In [12]:
a = np.random.randint(1, 10, (3,3))
print(a)
print(a.T) # 전치행렬

[[5 3 8]
 [6 1 2]
 [8 9 6]]
[[5 6 8]
 [3 1 9]
 [8 2 6]]

In [15]:
# 배열 형태 변경 : .ravel()

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.ravel()
b[0] = 10
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]

In [18]:
# reshape
x = np.arange(20)
y = x.reshape(4,5)
print(x)
print(y)

x[0] = 10
print(x)
print(y)

y[0,0] = 0
print(y)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [19]:
# 다차원 list를 reshape 하기
l1 = [1,2,3,4,5,6]
l2 = l1.reshape(3,2)

AttributeError: 'list' object has no attribute 'reshape'

In [24]:
# 다차원 list를 reshape 하기
l1 = [1,2,3,4,5,6]
d = np.array(l1)
print(type(d))
print(d)
print(d.reshape(3,2))
print(l1)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]

배열요소 추가및 삭제
  - np.resize(a, new)
  - np.ndarray.resize(new, refcheck = True)
  - 배열의 shape와 크기를 변경

In [26]:
# resize() : 요소가 동일한 경우 reshape()와 같다
a = np.arange(20)
y = np.resize(a, (5,4))
print(y)
y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
# resize() : 요소가 더 많은 경우 -> recursive 된다
a = np.arange(20)
y = np.resize(a, (5,6))
print(y)
y

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9]])

In [32]:
# resize와 reshape의 차이
x = np.arange(20)
y = x.reshape(4,5)
z = np.resize(x, (4,5))

print(x)
print(y)
print(z)

x[0] = 10
print(x)
print(y)
print(z)

y[0,0] = 100
print(x)
print(y)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

배열 요소 추가및 삭제
  - np.append(arr, values, axis=None)
  - 배열의 끝에 값을 추가

In [34]:
# 값 추가
a = np.arange(3)
print(a)
b = np.append(a, 3)
print(b)

[0 1 2]
[0 1 2 3]

In [36]:
# 배열추가
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6 7 8 9]

In [38]:
# 축(axis) 추가
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
c = np.append(a, b, axis = 0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [39]:
# 축(axis) 추가
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
c = np.append(a, b, axis = 1)
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

  - np.insert(arr, obj, values, axis=None)
    1. axis를 지정하지 않으면 1차원 배열로 변환
    2. 추가할 방향을 axis로 지정

In [40]:
# 값 추가 : 축지정
a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a, 1, 5, axis = 0)
c = np.insert(a, 1, 5, axis = 1)
print(a)
print(b)
print(c)

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [5 5]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 5 2]
 [3 5 3]]

In [43]:
# 값 추가 : 1차원 배열
a = np.array([1,2,3])
b = np.insert(a, 1, 5)
print(a)
print(b)
b = np.insert(b, 2, 6)
print(b)

[1 2 3]
[1 5 2 3]
[1 5 6 2 3]

배열 요소 삭제
  - np.delete(arr, obj, axis=None)
    1. axis 지정하지 않으면 1차원 배열로 변환
    2. 삭제할 방향을 axis로 지정
    3. delete함수는 원본 배열을 변경하지 않으면 새로운 배열을 반환

In [44]:
# 값 삭제
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a, 5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]

In [45]:
# 값 삭제 : 축지정
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a, 1, axis = 0))
print(np.delete(a, 1, axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]

배열 결합

In [46]:
# concatenate()
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
arr = np.concatenate((a1, a2))
print(arr)

[1 2 3 4 5 6]

In [47]:
# concatenate() : 축지정
a1 = np.array([[1,2,3]])
a2 = np.array([[4,5,6]])
arr = np.concatenate((a1, a2), axis = 0)
arr1 = np.concatenate((a1, a2), axis = 1)
print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]

 - np.vstack(튜플)
  1. 튜플로 설정된 여러 배열을 수직방향으로 연결(axis=0)
  2. np.concatenate(tup, axis=0)

 - np.hstack(튜플)
  1. 튜플로 설정된 여러 배열을 수평방향으로 연결(axis=1)
  2. np.concatenate(tup, axis=1)

In [49]:
a1 = np.array([[1,2,3]])
a2 = np.array([[4,5,6]])

print(np.vstack((a1, a2)))
print(np.concatenate((a1, a2), axis = 0))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

In [50]:
a1 = np.array([[1,2,3]])
a2 = np.array([[4,5,6]])

print(np.hstack((a1, a2)))
print(np.concatenate((a1, a2), axis = 1))

[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]

In [52]:
# 배열 분리
#   - np.hsplit(), np.vsplit()

a = np.arange(16).reshape(4,4)
a_hsplit = np.hsplit(a, 2)
print(a)
print(a_hsplit)

a_vsplit = np.vsplit(a, 2)
print(a_vsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

판다스
  - 고수준의 자료구조와 빠르고 쉬운 데이터 분석도구를 제공하는 파이썬 라이브러리
  - 자동적/ 명시적으로 축의 이름에 따라 데이터를 정할 수 있는 데이터 구조
  - import pandas as pd

In [53]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

- Series와 DataFrame
  1. Series : 다양한 자료형을 담을 수 있는 1차원 배열
  2. DataFrame : 행과 열을 갖는 2차원 자료형

- series + series = dataframe

In [55]:
import pandas as pd

# 실수형 시리즈
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
print(s)
s

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

In [56]:
# 인덱스 지정
s = pd.Series([90,80,75], index = ['A','B','C'])
s

A    90
B    80
C    75
dtype: int64

In [60]:
# 넘파이로 배열 생성
import numpy as np
import pandas as pd

arr = np.arange(12).reshape(4,3)
print(arr)
df = pd.DataFrame(arr)
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [62]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
s = pd.Series(arr)
s

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
dtype: int64

In [63]:
df = pd.DataFrame(arr)
print(df)
df

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11

In [64]:
# 딕셔너리로 배열 생성
df = pd.DataFrame({'name':['홍길동','고길동','둘리'], 'score':[90,80,70], 'dept':['com','eng','math']})
df

  name  score  dept
0  홍길동     90   com
1  고길동     80   eng
2   둘리     70  math

csv 활용
  - 데이터를 DataFrame으로 불러올 수 있다.

코랩에서 파일을 노에 업로드하는 방법

In [66]:
from google.colab import drive

drive.mount('/content/drive')
mob = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/img_detect/mobile.csv')

Mounted at /content/drive

In [67]:
mob

     Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [68]:
# csv 파일 불러 오 때 인덱스 지정
mob = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/img_detect/mobile.csv', index_col = 0)
mob

          Color  price
Brand
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

판다스 데이터 확인
  - 판다스 객체의 데이터를 확인하는 방법

csv 파일의 컬럼명이 한글인 경우
  - df = pd.read_csv("파일명", encoding="euc-kr")
  - df = pd.read_csv("파일명", encoding="cp949")

In [69]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset_sc/weather.csv')
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [70]:
# df.shape : 데이터의 (행, 열) 크기 확인
# df.info() : 데이터 정보 확인

df.shape

(3653, 4)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3653 non-null   object
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), object(1)
memory usage: 114.3+ KB

In [72]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [73]:
df.tail()

            date  temp  max_wind  mean_wind
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [74]:
# df.index/ df.columns
# 인덱스(행이름)와 열의 레이블(컬럼이름) 출력
df.index

RangeIndex(start=0, stop=3653, step=1)

In [75]:
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='object')

In [76]:
# df.describe() : 데이터의 요약 통계량
df.describe()

              temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

df.sort_values()
  - DataFrame.sort_values(by=['정렬변수', ...], ascending=False, inplace = True)

In [77]:
df.sort_values(by='max_wind')

            date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1005  2013-05-02   7.1       2.2        0.8
1512  2014-09-21  20.4       2.2        1.2
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [78]:
df.sort_values(by='max_wind', ascending=False)

            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [79]:
# df.value_counts() : 범주형 변수의 빈도분석 결과 출력
bank = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset_sc/bank.csv')
bank['job'].value_counts()

job
management       1560
blue-collar      1499
technician       1206
admin.            834
services          661
retired           351
self-employed     256
entrepreneur      239
unemployed        223
housemaid         208
student           153
Name: count, dtype: int64

In [80]:
bank['job'].value_counts(ascending=True)

job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

In [81]:
# df.unique() : 해당 열의 고유값 확인
bank['job'].unique()

array(['management', 'technician', 'blue-collar', 'retired', 'services',
       'admin.', 'entrepreneur', 'self-employed', 'unemployed', 'student',
       nan, 'housemaid'], dtype=object)

  - 데이터 선택
    1. 열선택
    2. 행선택

열선택
  1. 하나의 Series를 만든다
  2. df[컬럼명] or df.컬럼명

In [83]:
# 단일 컬럼 선택
df['temp']
df.temp

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [84]:
# 여러 컬럼 선택
df[['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [86]:
# 여러컬럼 선택 : loc()
df.loc[:, ['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [87]:
# 여러컬럼 선택 : iloc()
# df.iloc[:, ['date', 'temp]]  X
df.iloc[:, [0, 1]]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

행 선택하기
  - 인덱스 숫자를 사용하면 행을 슬라이스

In [88]:
# 특정 범위 선택
df[0:3]

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [89]:
# 레이블로 선택하기 : df.loc

# 특정 날짜에 해당하는 열 선택

df.index = df['date']
df.loc['2010-08-01', ['temp', 'mean_wind']]

temp         28.7
mean_wind     3.4
Name: 2010-08-01, dtype: object

In [90]:
# 위치로 선택 : df.iloc
# 정수를 입력하면 해당 행을 선택

# 특정 행 선택
df.iloc[3]

date         2010-08-04
temp               25.3
max_wind            6.6
mean_wind           4.2
Name: 2010-08-04, dtype: object

In [91]:
# 특정 행과 열 선택 : 슬라이싱
df.iloc[1:3, 0:2]

                  date  temp
date
2010-08-02  2010-08-02  25.2
2010-08-03  2010-08-03  22.1